### ISSUE TITLE
Mail broke

### ISSUE THREAD

**Issue by Sonic4Tails** [zefie/zefie_wtvp_minisrv#10]
When trying to send mail it previously worked fine but now it just error out

```
 * Request for wtv-mail:/content/images/RemoveButton.gif from WebTV SSID Cookie********* on 60071
 * Sent 200 OK to client (Content-Type: image/gif ~ 484 bytes)
 * Incoming POST request on 51941 from Cookie********* to wtv-mail:/sendmail (expecting 141 bytes of data from client...)
 * Received 100 % of 141 bytes on 51941 from Cookie*********
 # Unencrypted POST Content on 51941
 * Request for wtv-mail:/sendmail from WebTV SSID Cookie********* on 51941
Error: connect ECONNREFUSED 127.0.0.1:119
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 119
}
Error: connect ECONNREFUSED 127.0.0.1:119
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
usenet upstream uncaught error Error: connect ECONNREFUSED 127.0.0.1:119
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 119
}
ReferenceError: clientErrorMsg is not defined
    at C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\ServiceVault\wtv-mail\sendmail.js:172:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ReferenceError: clientErrorMsg is not defined
    at C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\ServiceVault\wtv-mail\sendmail.js:172:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 * Decoded session from wtv-ticket with ticket_store: { user_id: '0' }
 # Generating RC4 sessions with wtv-incarnation: 38
 # [ SECURE ON BLOCK (56027) ]
 # Encrypted Request (SECURE ON) on 56027
 * Encrypted Request for wtv-home:/home from WebTV SSID Cookie********* on 56027
 # Compression stats: Orig Size: 13335 ~ Comp Size: 2523 ~ Ratio: 5.29 ~ Saved: 81.1%
 * Sent encrypted response 200 OK to client (Content-Type: text/html ~ 2523 bytes)
 * Request for wtv-star:/ROMCache/MSNLogo.gif from WebTV SSID Cookie********* on 60071
 * Sent 200 OK to client (Content-Type: image/gif ~ 1801 bytes)
```

**Comment by zefie** [comment]
Should be fixed in 1752bfed353d618dfa27ce89eb964f786d04f5b8
