### ISSUE TITLE
when trying to remove an user i get the following (i have not messed with the wtvclientsessiondata.js file)

### ISSUE THREAD

**Issue by Sonic4Tails** [zefie/zefie_wtvp_minisrv#8]
* doErrorPage Called: 400 HackTV ran into a technical problem.
 * Scripting error: TypeError: this.fs.rmSync is not a function
    at WTVClientSessionData.removeUser (C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\WTVClientSessionData.js:190:21)
    at eval (eval at <anonymous> (C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\app.js:266:21), <anonymous>:60:31)
    at Array.forEach (<anonymous>)
    at eval (eval at <anonymous> (C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\app.js:266:21), <anonymous>:59:30)
    at C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\app.js:266:21
    at Array.forEach (<anonymous>)
    at processPath (C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\app.js:111:24)
    at processURL (C:\Users\purpe\Documents\revivals\FaithTV\zefie_wtvp_minisrv\app.js:496:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 * Sent encrypted response 400 HackTV ran into a technical problem. to client (Content-Type: text/html ~ 123 bytes)

**Comment by zefie** [comment]
Couldn't replicate on current dev commit so assuming this was fixed
